/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "common.h"

float rpm;

int main(void) {

	if (!cpuFreqInit(PLL_SOURCE)) {

		for(uint8_t i = 0; i < 25; i++) {

			GPIOC->ODR ^= GPIO_ODR_ODR13;
			for(uint32_t i = 0; i < 100000; i++) {

				__NOP();
			}
		}
	}
	userLedInit();
	dcMotorPwmInit();
	dcMotorRun();
	encoderTimInit();

	for (;;) {

		rpm = encoderGetRPM();
		userLedToggle(LED_ON);
		delayMs(1000);
		userLedToggle(LED_OFF);
		delayMs(1000);
	}
}
